// <auto-generated />
namespace Matterspace.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeowneridfromproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeowneridfromproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201611132150090_remove-ownerid-from-product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
