// <auto-generated />
namespace Matterspace.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixingusertypeonstatuschangeevent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixingusertypeonstatuschangeevent));
        
        string IMigrationMetadata.Id
        {
            get { return "201611132319102_fixing-user-type-on-status-change-event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
